\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		c1 a1:m f2 g2 c1 c1

		% estribillo
		c1 a1:m f1 g1
		c1 a1:m f2 g2 c1 c1

		% tú que me conduces...
		c1 a1:m f1 g1
		f1 c1 f1 g1 g1

		% estribillo
		c1 a1:m f1 g1
		c1 a1:m f2 g2 c1 c1

		% tú que me preparas...
		c1 a1:m f1 g1
		f1 c1 f1 g1 g1

		% estribillo
		c1 a1:m f1 g1
		c1 a1:m f2 g2 c1 c1

		% tu bondad conmigo...
		c1 a1:m f1 g1
		f1 c1 f1 g1 g1

		% estribillo final
		c1 a1:m f1 g1
		c1 a1:m f2 g2 c1
		f2 g2 c1
		f2 g8 g8 r4
		c1
	}
